DF_SETUP_STARSHIP="true"
DF_SETUP_DOCKER="true"
DF_SETUP_SDKMAN="true"
DF_SETUP_JB_TOOLBOX="true"
DF_SETUP_QUARKUS="true"
DF_SETUP_NODEJS="true"
DF_SETUP_BUN="true"
DF_SETUP_DENO="true"
DF_SETUP_CODEX="true"
DF_SETUP_GOLANG="false"
DF_SETUP_SUBLIME="true"
DF_SETUP_VSCODE="true"
DF_SETUP_ZED="true"

# DF_NODEJS_VERSION="22.9.0"

# ensure all built images use amd64 instead of arm64
DF_FORCE_AMD64_DOCKER="false"
