#!/usr/bin/env zsh

cat <<- HERE
-------------------------------------------------------------------------------
Installing dotfiles!
-------------------------------------------------------------------------------

HERE

dotfiles_dir="${0:a:h}"

# ln -snf "$dotfiles_dir/bin" "$HOME/bin"

if [ ! -z $DOCKER_IMAGE_NAME ]; then
	ln -snf "$dotfiles_dir/init" "/etc/profile.d/init"
elif [ "$(uname -s)" = "Linux" ] || [ "$(uname -s)" = "Darwin" ]; then

	if [ ! -f "$HOME/.zprofile" ]; then
		touch "$HOME/.zprofile"
	fi

	if [ ! -f "$HOME/.zshrc" ]; then
		touch "$HOME/.zshrc"
	fi

	zshrc_line="$(grep -n "export DOTFILES_DIR" "$HOME/.zshrc" | awk -F ":" '{print $1}')"

	if [ ! -z "$zshrc_line" ]; then
		# delete old lines in .zshrc
		mv "$HOME/.zshrc" "$HOME/.zshrc.bak"
		sed "${zshrc_line},${zshrc_line}d" "$HOME/.zshrc.bak" > "$HOME/.zshrc"
	fi

	# add to top of .zshrc
	cat <<- HERE > "$HOME/.zshrc.tmp"
	export DOTFILES_DIR="$dotfiles_dir"; [ -f "\$DOTFILES_DIR/init" ] && . "\$DOTFILES_DIR/init"; autoload -Uz compinit && compinit
	HERE
	cat "$HOME/.zshrc" >> "$HOME/.zshrc.tmp"
	mv "$HOME/.zshrc.tmp" "$HOME/.zshrc"

	if [ "$(uname -s)" = "Linux" ]; then
		cat <<- HERE
		"$HOME/.zprofile" and "$HOME/.zshrc" have been updated!
		Please log out and log back in for changes to take affect.
		HERE
	else
		# Non-Linux OS's handle .profile during shell startup rather than a real user 
		# login. Any new terminal windows will automatically source the user's updated 
		# .profile. Ensure the current terminal window has the .profile sourced.

		cat <<- HERE
		"$HOME/.zprofile" and "$HOME/.zshrc" have been updated!
		Please close and open a new terminal window for changes to take affect.
		HERE
	fi
fi

cat <<- HERE

-------------------------------------------------------------------------------
Finished!
-------------------------------------------------------------------------------
HERE

