# Helpers shared by install-bash and install-zsh. POSIX sh - sourced by both, so
# it has to run under bash and zsh alike.

df_install_begin="# BEGIN: autogenerated from dotfiles.git/install                               #"
df_install_end="# END: autogenerated from dotfiles.git/install                                 #"
df_install_rule="################################################################################"

# the marker text without the padding - what a previous run's line is matched on.
# deliberately stops before "-bash"/"-zsh" so blocks written by either installer,
# including older ones that named the script, are recognized
df_install_match="autogenerated from dotfiles.git/install"

df-install-banner() {
	cat <<-HERE
		-------------------------------------------------------------------------------
		Installing dotfiles!
		-------------------------------------------------------------------------------

	HERE
}

df-install-finished() {
	cat <<-HERE

		-------------------------------------------------------------------------------
		Finished!
		-------------------------------------------------------------------------------
	HERE
}

# df-install-updated <file>...
# Report what changed and how the user picks it up.
df-install-updated() {
	echo "Updated:"
	for df_updated in "$@"; do
		echo "  $df_updated"
	done
	unset df_updated

	if [ "$(uname -s)" = "Linux" ]; then
		cat <<-HERE

			Please log out and log back in for changes to take affect.
		HERE
	else
		# Non-Linux OS's handle .profile during shell startup rather than a real
		# user login. Any new terminal windows will automatically source the
		# user's updated .profile.
		cat <<-HERE

			Please close and open a new terminal window for changes to take affect.
		HERE
	fi
}

# df-strip-blank-lines
# Drop leading and trailing blank lines from stdin. Without this the blank line
# that separates the block from the rest of the file is kept on re-read and a
# fresh one added, so the file grows a line every run.
df-strip-blank-lines() {
	awk '
		{ line[NR] = $0; if (NF) { if (!first) first = NR; last = NR } }
		END {
			if (!first) exit
			for (i = first; i <= last; i++) print line[i]
		}
	'
}

# df-install-block <file> [top|bottom]
# Replace the block this repo owns in <file> with the content on stdin, wrapped
# in BEGIN/END markers. Anything outside the markers is left alone, so it is safe
# to re-run and safe on a file the user also edits by hand. Defaults to bottom;
# use top for files whose block defines things the rest of the file builds on.
df-install-block() {
	df_block_file="$1"
	df_block_position="${2:-bottom}"

	if [ ! -f "$df_block_file" ]; then
		touch "$df_block_file"
	fi

	# keep everything the previous run did not write. \|...| rather than /.../
	# because the marker text itself contains a "/"
	mv "$df_block_file" "$df_block_file.bak"
	sed "\|$df_install_match|,\|$df_install_match|d" "$df_block_file.bak" |
		df-strip-blank-lines >"$df_block_file.keep"

	{
		if [ "$df_block_position" = "top" ]; then
			echo "$df_install_begin"
			echo "$df_install_rule"
			echo
			cat
			echo
			echo "$df_install_rule"
			echo "$df_install_end"
			if [ -s "$df_block_file.keep" ]; then
				echo
				cat "$df_block_file.keep"
			fi
		else
			if [ -s "$df_block_file.keep" ]; then
				cat "$df_block_file.keep"
				echo
			fi
			echo "$df_install_begin"
			echo "$df_install_rule"
			echo
			cat
			echo
			echo "$df_install_rule"
			echo "$df_install_end"
		fi
	} >"$df_block_file.tmp"

	rm -f "$df_block_file.keep"
	mv "$df_block_file.tmp" "$df_block_file"

	unset df_block_file df_block_position
}
